---
- hosts: all
  become: true
  tasks:
    # - name: update repository index
    #   apt:
    #     update_cache: yes

    # state: absent (for "remove")

    # - name: install apache2 package
    #   apt:
    #     name: apache2
    #     state: latest

    - name: remove apache2 package
      apt:
        name: apache2
        state: absent
